resource_registry:
  # yamllint disable rule:line-length
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::OVNMacAddressNetwork: OS::Heat::None
  OS::TripleO::OVNMacAddressPort: OS::Heat::None
  OS::TripleO::ComputeRack1::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::ComputeRack1::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::ComputeRack1::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::ComputeRack2::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::ComputeRack2::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::ComputeRack2::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::ComputeRack3::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::ComputeRack3::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::ComputeRack3::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::ControllerRack1::Ports::ExternalPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_external.yaml
  OS::TripleO::ControllerRack1::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::ControllerRack1::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::ControllerRack1::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::ControllerRack2::Ports::ExternalPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_external.yaml
  OS::TripleO::ControllerRack2::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::ControllerRack2::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::ControllerRack2::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::ControllerRack3::Ports::ExternalPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_external.yaml
  OS::TripleO::ControllerRack3::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::ControllerRack3::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::ControllerRack3::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::Services::OsloMessagingRpc: /usr/share/openstack-tripleo-heat-templates/deployment/rabbitmq/rabbitmq-messaging-rpc-pacemaker-puppet.yaml
  OS::TripleO::Services::OsloMessagingNotify: /usr/share/openstack-tripleo-heat-templates/deployment/rabbitmq/rabbitmq-messaging-notify-shared-puppet.yaml
  OS::TripleO::Services::HAproxy: /usr/share/openstack-tripleo-heat-templates/deployment/haproxy/haproxy-pacemaker-puppet.yaml
  OS::TripleO::Services::Pacemaker: /usr/share/openstack-tripleo-heat-templates/deployment/pacemaker/pacemaker-baremetal-puppet.yaml
  OS::TripleO::Services::PacemakerRemote: /usr/share/openstack-tripleo-heat-templates/deployment/pacemaker/pacemaker-remote-baremetal-puppet.yaml
  OS::TripleO::Services::Clustercheck: /usr/share/openstack-tripleo-heat-templates/deployment/pacemaker/clustercheck-container-puppet.yaml
  OS::TripleO::Services::Redis: /usr/share/openstack-tripleo-heat-templates/deployment/database/redis-pacemaker-puppet.yaml
  OS::TripleO::Services::Rsyslog: /usr/share/openstack-tripleo-heat-templates/deployment/logging/rsyslog-container-puppet.yaml
  OS::TripleO::Services::MySQL: /usr/share/openstack-tripleo-heat-templates/deployment/database/mysql-pacemaker-puppet.yaml
  OS::TripleO::Services::CinderBackup: /usr/share/openstack-tripleo-heat-templates/deployment/cinder/cinder-backup-pacemaker-puppet.yaml
  OS::TripleO::Services::CinderVolume: /usr/share/openstack-tripleo-heat-templates/deployment/cinder/cinder-volume-pacemaker-puppet.yaml
  OS::TripleO::Services::HeatApi: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-api-container-puppet.yaml
  OS::TripleO::Services::HeatApiCfn: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-api-cfn-container-puppet.yaml
  OS::TripleO::Services::HeatApiCloudwatch: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-api-cloudwatch-disabled-puppet.yaml
  OS::TripleO::Services::HeatEngine: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-engine-container-puppet.yaml

  # workarounds
  OS::TripleO::ControllerRack1ExtraConfigPre: /home/stack/tht/extraconfigpre_template.yaml
  OS::TripleO::ControllerRack2ExtraConfigPre: /home/stack/tht/extraconfigpre_template.yaml
  OS::TripleO::ControllerRack3ExtraConfigPre: /home/stack/tht/extraconfigpre_template.yaml
  OS::TripleO::ComputeRack1ExtraConfigPre: /home/stack/tht/extraconfigpre_template.yaml
  OS::TripleO::ComputeRack2ExtraConfigPre: /home/stack/tht/extraconfigpre_template.yaml
  OS::TripleO::ComputeRack3ExtraConfigPre: /home/stack/tht/extraconfigpre_template.yaml

  OS::TripleO::NodeExtraConfigPost: /home/stack/tht/extraconfigpost_template.yaml

parameter_defaults:
  OvercloudControllerRack1Flavor: control1
  OvercloudControllerRack2Flavor: control2
  OvercloudControllerRack3Flavor: control3
  ControllerRack1Count: 1
  ControllerRack2Count: 1
  ControllerRack3Count: 1
  OvercloudComputeRack1Flavor: compute1
  OvercloudComputeRack2Flavor: compute2
  OvercloudComputeRack3Flavor: compute3
  ComputeRack1Count: 2
  ComputeRack2Count: 2
  ComputeRack3Count: 2
  ControllerRack1ControlPlaneSubnet: r1
  ControllerRack2ControlPlaneSubnet: r2
  ControllerRack3ControlPlaneSubnet: r3
  ComputeRack1ControlPlaneSubnet: r1
  ComputeRack2ControlPlaneSubnet: r2
  ComputeRack3ControlPlaneSubnet: r3

  # extraconfigpre
  ContainerHealthcheckDisabled: true
  Debug: true
  ConfigDebug: true
  CephAnsiblePlaybookVerbosity: 2
  CloudDomain: "{{ ansible_domain }}"
  CloudName: "overcloud.{{ ansible_domain }}"
  CloudNameCtlplane: "overcloud.ctlplane.{{ ansible_domain }}"
  CloudNameMainNetwork: "overcloud.main.{{ ansible_domain }}"
  CloudNameLeftNetwork: "overcloud.left.{{ ansible_domain }}"
  CloudNameRightNetwork: "overcloud.right.{{ ansible_domain }}"

  # Issue 84. in the rhel9 issue doc (vms do not boot)
  IronicDefaultBootMode: 'bios'

  SkipRhelEnforcement: 'true'
  TimeZone: UTC
  CinderLVMLoopDeviceSize: 16384
  FrrBfdEnabled: true
  FrrBgpEnabled: true
  FrrBgpIpv4AllowASIn: true
  FrrBgpIpv6AllowASIn: true
  FrrBgpUplinks: ['nic2', 'nic3']
  FrrBgpUplinksScope: internal
  FrrLogLevel: debugging
  FrrBgpIpv4SrcNetwork: main_network
  FrrBgpIpv6SrcNetwork: main_network_ipv6
  FrrBgpL2VpnEnabled: true
  FrrBgpL2VpnEbgpMultihop: 10
  FrrBgpL2VpnPeers: ['5.1.1.1']

  ControllerRack1ExtraGroupVars:
    tripleo_frr_bgp_neighbor_password: f00barZ
    tripleo_frr_bfd_detect_multiplier: 10
    tripleo_frr_bfd_transmit_interval: 500
    tripleo_frr_bfd_receive_interval: 500
    tripleo_frr_zebra_graceful_restart_time: 30
    tripleo_frr_conf_custom_router_bgp: |
      bgp graceful-restart
    tripleo_frr_conf_custom_globals: |
      debug bfd peer
      debug bfd network
      debug bfd zebra
      debug bgp graceful-restart
      debug bgp neighbor-events
      debug bgp updates
      debug bgp update-groups
  ControllerRack2ExtraGroupVars:
    tripleo_frr_bgp_neighbor_password: f00barZ
    tripleo_frr_bfd_detect_multiplier: 10
    tripleo_frr_bfd_transmit_interval: 500
    tripleo_frr_bfd_receive_interval: 500
    tripleo_frr_zebra_graceful_restart_time: 30
    tripleo_frr_conf_custom_router_bgp: |
      bgp graceful-restart
    tripleo_frr_conf_custom_globals: |
      debug bfd peer
      debug bfd network
      debug bfd zebra
      debug bgp graceful-restart
      debug bgp neighbor-events
      debug bgp updates
      debug bgp update-groups
  ControllerRack3ExtraGroupVars:
    tripleo_frr_bgp_neighbor_password: f00barZ
    tripleo_frr_bfd_detect_multiplier: 10
    tripleo_frr_bfd_transmit_interval: 500
    tripleo_frr_bfd_receive_interval: 500
    tripleo_frr_zebra_graceful_restart_time: 30
    tripleo_frr_conf_custom_router_bgp: |
      bgp graceful-restart
    tripleo_frr_conf_custom_globals: |
      debug bfd peer
      debug bfd network
      debug bfd zebra
      debug bgp graceful-restart
      debug bgp neighbor-events
      debug bgp updates
      debug bgp update-groups
  ComputeRack1ExtraGroupVars:
    tripleo_frr_bgp_neighbor_password: f00barZ
    tripleo_frr_bfd_detect_multiplier: 10
    tripleo_frr_bfd_transmit_interval: 500
    tripleo_frr_bfd_receive_interval: 500
    tripleo_frr_zebra_graceful_restart_time: 30
    tripleo_frr_conf_custom_router_bgp: |
      bgp graceful-restart
    tripleo_frr_conf_custom_globals: |
      debug bfd peer
      debug bfd network
      debug bfd zebra
      debug bgp graceful-restart
      debug bgp neighbor-events
      debug bgp updates
      debug bgp update-groups
  ComputeRack2ExtraGroupVars:
    tripleo_frr_bgp_neighbor_password: f00barZ
    tripleo_frr_bfd_detect_multiplier: 10
    tripleo_frr_bfd_transmit_interval: 500
    tripleo_frr_bfd_receive_interval: 500
    tripleo_frr_zebra_graceful_restart_time: 30
    tripleo_frr_conf_custom_router_bgp: |
      bgp graceful-restart
    tripleo_frr_conf_custom_globals: |
      debug bfd peer
      debug bfd network
      debug bfd zebra
      debug bgp graceful-restart
      debug bgp neighbor-events
      debug bgp updates
      debug bgp update-groups
  ComputeRack3ExtraGroupVars:
    tripleo_frr_bgp_neighbor_password: f00barZ
    tripleo_frr_bfd_detect_multiplier: 10
    tripleo_frr_bfd_transmit_interval: 500
    tripleo_frr_bfd_receive_interval: 500
    tripleo_frr_zebra_graceful_restart_time: 30
    tripleo_frr_conf_custom_router_bgp: |
      bgp graceful-restart
    tripleo_frr_conf_custom_globals: |
      debug bfd peer
      debug bfd network
      debug bfd zebra
      debug bgp graceful-restart
      debug bgp neighbor-events
      debug bgp updates
      debug bgp update-groups

  BgpvpnServiceProvider: 'BGPVPN:OVN:networking_bgpvpn.neutron.services.service_drivers.ovn.ovn.OvnBGPVPNDriver:default'

  ControllerRack1SchedulerHints:
    'capabilities:node': 'ctrl-1-%index%'
  ControllerRack2SchedulerHints:
    'capabilities:node': 'ctrl-2-%index%'
  ControllerRack3SchedulerHints:
    'capabilities:node': 'ctrl-3-%index%'
  ComputeRack1SchedulerHints:
    'capabilities:node': 'cmp-1-%index%'
  ComputeRack2SchedulerHints:
    'capabilities:node': 'cmp-2-%index%'
  ComputeRack3SchedulerHints:
    'capabilities:node': 'cmp-3-%index%'

  ExtraConfig:
    neutron::config::plugin_ml2_config:
      OVN/ovsdb_log_level:
        value: DEBUG

  # Allow ssh access from all networks
  SshFirewallAllowAll: true
  MemcachedIpSubnet: '172.16.0.0/12'

  BarbicanSimpleCryptoGlobalDefault: true
