parameter_defaults:

  ControllerRack0IPs:
    left_network:
    - 100.64.0.30
    right_network:
    - 100.65.0.30
    main_network:
    - 99.99.0.29/24
  ControllerRack1IPs:
    left_network:
    - 100.64.1.30
    right_network:
    - 100.65.1.30
    main_network:
    - 99.99.1.30/24
  ControllerRack2IPs:
    left_network:
    - 100.64.2.30
    right_network:
    - 100.65.2.30
    main_network:
    - 99.99.2.29/24
  ComputeRack0IPs:
    left_network:
    - 100.64.0.2
    - 100.64.0.6
    right_network:
    - 100.65.0.2
    - 100.65.0.6
    main_network:
    - 99.99.0.2/24
    - 99.99.0.6/24
  ComputeRack1IPs:
    left_network:
    - 100.64.1.2
    - 100.64.1.6
    right_network:
    - 100.65.1.2
    - 100.65.1.6
    main_network:
    - 99.99.1.2/24
    - 99.99.1.6/24
  ComputeRack2IPs:
    left_network:
    - 100.64.2.2
    - 100.64.2.6
    right_network:
    - 100.65.2.2
    - 100.65.2.6
    main_network:
    - 99.99.2.2/24
    - 99.99.2.6/24


  # this overrides the default value openstacklocal
  NeutronDnsDomain: example.com

  # overriding default values in order to not collide with provider subnet
  OctaviaControlSubnetCidr: 172.25.0.0/16
  OctaviaControlSubnetGateway: 172.25.0.1
  OctaviaControlSubnetPoolStart: 172.25.0.2
  OctaviaControlSubnetPoolEnd: 172.25.255.254

  OctaviaLoadBalancerTopology: ACTIVE_STANDBY

  ControlPlaneSubnet: main_network_r0
  VipSubnetMap:
    main_network: main_network_r0
  # provider1 represents a flat network
  # provider2 represents a network with vlans
  NeutronFlatNetworks: provider1
  ControllerRack0Parameters:
    NeutronBridgeMappings: ["provider1:br-ex", "provider2:br-vlan"]
    ControlPlaneSubnet: main_network_r0
    OVNCMSOptions: "enable-chassis-as-gw"
    FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
    FrrOvnBgpAgentExposeTenantNetworks: True
    ExtraSysctlSettings:
      net.ipv6.conf.enp2s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.enp3s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.br-ex.router_solicitations:
        value: 0
  ControllerRack1Parameters:
    NeutronBridgeMappings: ["provider1:br-ex", "provider2:br-vlan"]
    ControlPlaneSubnet: main_network_r1
    OVNCMSOptions: "enable-chassis-as-gw"
    FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
    FrrOvnBgpAgentExposeTenantNetworks: True
    ExtraSysctlSettings:
      net.ipv6.conf.enp2s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.enp3s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.br-ex.router_solicitations:
        value: 0
  ControllerRack2Parameters:
    NeutronBridgeMappings: ["provider1:br-ex", "provider2:br-vlan"]
    ControlPlaneSubnet: main_network_r2
    OVNCMSOptions: "enable-chassis-as-gw"
    FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
    FrrOvnBgpAgentExposeTenantNetworks: True
    ExtraSysctlSettings:
      net.ipv6.conf.enp2s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.enp3s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.br-ex.router_solicitations:
        value: 0
  ComputeRack0Parameters:
    NeutronBridgeMappings: ["provider1:br-ex", "provider2:br-vlan"]
    FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
    ExtraSysctlSettings:
      net.ipv6.conf.enp2s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.enp3s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.br-ex.router_solicitations:
        value: 0
  ComputeRack1Parameters:
    NeutronBridgeMappings: ["provider1:br-ex", "provider2:br-vlan"]
    FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
    ExtraSysctlSettings:
      net.ipv6.conf.enp2s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.enp3s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.br-ex.router_solicitations:
        value: 0
  ComputeRack2Parameters:
    NeutronBridgeMappings: ["provider1:br-ex", "provider2:br-vlan"]
    FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
    ExtraSysctlSettings:
      net.ipv6.conf.enp2s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.enp3s0.accept_ra_defrtr:
        value: 0
      net.ipv6.conf.br-ex.router_solicitations:
        value: 0
  #NeutronEnableDVR: 'false'
  #NeutronNetworkType: 'geneve'
  #NeutronTunnelTypes: 'geneve'
  NeutronExternalNetworkBridge: ''
  NeutronNetworkVLANRanges: 'provider2:1:1000'
  DnsServers: ['192.168.122.1', '192.168.125.1']
  NtpPool: clock.corp.redhat.com
  EnableVLANTransparency: True
  NeutronEnableIgmpSnooping: True

  RedisVirtualFixedIPs:
    - ip_address: 172.31.0.3
      use_neutron: false

  ServiceNetMap:
    ApacheNetwork: main_network
    NeutronTenantNetwork: main_network
    AodhApiNetwork: main_network
    PankoApiNetwork: main_network
    BarbicanApiNetwork: main_network
    GnocchiApiNetwork: main_network
    MongodbNetwork: main_network
    CinderApiNetwork: main_network
    CinderIscsiNetwork: main_network
    GlanceApiNetwork: main_network
    GlanceApiEdgeNetwork: main_network
    GlanceApiInternalNetwork: main_network
    IronicApiNetwork: main_network
    IronicNetwork: main_network
    IronicInspectorNetwork: main_network
    KeystoneAdminApiNetwork: main_network
    KeystonePublicApiNetwork: main_network
    ManilaApiNetwork: main_network
    NeutronApiNetwork: main_network
    OctaviaApiNetwork: main_network
    HeatApiNetwork: main_network
    HeatApiCfnNetwork: main_network
    HeatApiCloudwatchNetwork: main_network
    NovaApiNetwork: main_network
    PlacementNetwork: main_network
    NovaMetadataNetwork: main_network
    NovaVncProxyNetwork: main_network
    NovaLibvirtNetwork: main_network
    NovajoinNetwork: main_network
    SwiftStorageNetwork: main_network
    SwiftProxyNetwork: main_network
    HorizonNetwork: main_network
    MemcachedNetwork: main_network
    OsloMessagingRpcNetwork: main_network
    OsloMessagingNotifyNetwork: main_network
    RabbitmqNetwork: main_network
    QdrNetwork: main_network
    RedisNetwork: main_network
    GaneshaNetwork: main_network
    MysqlNetwork: main_network
    SnmpdNetwork: main_network
    CephClusterNetwork: main_network
    CephDashboardNetwork: main_network
    CephGrafanaNetwork: main_network
    CephMonNetwork: main_network
    CephRgwNetwork: main_network
    PublicNetwork: main_network
    OpendaylightApiNetwork: main_network
    OvnDbsNetwork: main_network
    DockerRegistryNetwork: ctlplane
    PacemakerNetwork: main_network
    PacemakerRemoteNetwork: main_network
    DesignateApiNetwork: main_network
    BINDNetwork: main_network
    EtcdNetwork: main_network
    HaproxyNetwork: main_network

    # Not sure as to why yet, but without these we fail rendering the hosts entries
    ControllerRack1HostnameResolveNetwork: main_network
    ControllerRack2HostnameResolveNetwork: main_network
    ControllerRack3HostnameResolveNetwork: main_network
    ComputeRack1HostnameResolveNetwork: main_network
    ComputeRack2HostnameResolveNetwork: main_network
    ComputeRack3HostnameResolveNetwork: main_network
    InternalApiNetwork: main_network

    PublicNetwork: external
    #PublicNetwork: ctlplane
